[package]
name = "m_calc"
version = "0.1.0"
authors = ["lomotos10"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "2.0"
itertools = "0.10.0"